"""empty message

Revision ID: c27bdd7da946
Revises: 73af3b03729e
Create Date: 2024-03-03 12:30:07.115811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27bdd7da946'
down_revision: Union[str, None] = '73af3b03729e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('date_of_book', sa.Date(), nullable=False))
    op.alter_column('book', 'checked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('book', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('book', 'checked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('book', 'date_of_book')
    # ### end Alembic commands ###
